version: '2'

services:
  nginx:
    image: nginx:1.14
    volumes:
      - ./docker/nginx/sites-enabled:/etc/nginx/conf.d
      - ./www:/var/www
    working_dir: /etc/nginx
    tty: true
    stdin_open: true
    ports:
      - '84:80'
    depends_on:
      - python

  python:
    build:
      context: ./docker/python
    working_dir: /srv/interview
    volumes:
      - ./srv:/srv/interview
    env_file: ./.env
    stdin_open: true
    tty: true
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
